export default {
  type: 'root',
  file: '-virtual/root.tsx',
  children: [
    { type: 'index', file: '-virtual/index.tsx' },
    { type: 'route', path: '/ar', file: '-virtual/ar-index.tsx' },
    { type: 'route', path: '/en/image-compressor', file: '-virtual/en-image-compressor.tsx' },
    { type: 'route', path: '/ar/image-compressor', file: '-virtual/ar-image-compressor.tsx' },
    { type: 'route', path: '/en/quickflow', file: '-virtual/en-quickflow.tsx' },
    { type: 'route', path: '/ar/quickflow', file: '-virtual/ar-quickflow.tsx' },
    { type: 'route', path: '/en/use-case', file: '-virtual/en-use-case.tsx' },
    { type: 'route', path: '/ar/use-case', file: '-virtual/ar-use-case.tsx' },
    { type: 'route', path: '/en/background-remover', file: '-virtual/en-background-remover.tsx' },
    { type: 'route', path: '/ar/background-remover', file: '-virtual/ar-background-remover.tsx' },
    { type: 'route', path: '/en/ai-image-generator', file: '-virtual/en-ai-image-generator.tsx' },
    { type: 'route', path: '/ar/ai-image-generator', file: '-virtual/ar-ai-image-generator.tsx' },
    { type: 'route', path: '/en/image-upscaler', file: '-virtual/en-image-upscaler.tsx' },
    { type: 'route', path: '/ar/image-upscaler', file: '-virtual/ar-image-upscaler.tsx' },
    { type: 'route', path: '/en/image-converter', file: '-virtual/en-image-converter.tsx' },
    { type: 'route', path: '/ar/image-converter', file: '-virtual/ar-image-converter.tsx' },
    { type: 'route', path: '/en/image-to-text', file: '-virtual/en-image-to-text.tsx' },
    { type: 'route', path: '/ar/image-to-text', file: '-virtual/ar-image-to-text.tsx' },
    { type: 'route', path: '/en/object-remover', file: '-virtual/en-object-remover.tsx' },
    { type: 'route', path: '/ar/object-remover', file: '-virtual/ar-object-remover.tsx' },
    { type: 'route', path: '/en/crop-resize', file: '-virtual/en-crop-resize.tsx' },
    { type: 'route', path: '/ar/crop-resize', file: '-virtual/ar-crop-resize.tsx' },
    { type: 'route', path: '/en/watermark-remover', file: '-virtual/en-watermark-remover.tsx' },
    { type: 'route', path: '/ar/watermark-remover', file: '-virtual/ar-watermark-remover.tsx' },
    { type: 'route', path: '/en/raster-to-svg', file: '-virtual/en-raster-to-svg.tsx' },
    { type: 'route', path: '/ar/raster-to-svg', file: '-virtual/ar-raster-to-svg.tsx' },
    { type: 'route', path: '/en/image-cropper', file: '-virtual/en-image-cropper.tsx' },
    { type: 'route', path: '/ar/image-cropper', file: '-virtual/ar-image-cropper.tsx' },
    { type: 'route', path: '/en/image-ocr', file: '-virtual/en-image-ocr.tsx' },
    { type: 'route', path: '/ar/image-ocr', file: '-virtual/ar-image-ocr.tsx' },
    { type: 'route', path: '/en/photo-colorizer', file: '-virtual/en-photo-colorizer.tsx' },
    { type: 'route', path: '/ar/photo-colorizer', file: '-virtual/ar-photo-colorizer.tsx' },
    { type: 'route', path: '/en/background-blur', file: '-virtual/en-background-blur.tsx' },
    { type: 'route', path: '/ar/background-blur', file: '-virtual/ar-background-blur.tsx' },
    { type: 'route', path: '/en/passport-photo-maker', file: '-virtual/en-passport-photo-maker.tsx' },
    { type: 'route', path: '/ar/passport-photo-maker', file: '-virtual/ar-passport-photo-maker.tsx' },
    { type: 'route', path: '/en/watermark-adder', file: '-virtual/en-watermark-adder.tsx' },
    { type: 'route', path: '/ar/watermark-adder', file: '-virtual/ar-watermark-adder.tsx' },
    { type: 'route', path: '/en/meme-generator', file: '-virtual/en-meme-generator.tsx' },
    { type: 'route', path: '/ar/meme-generator', file: '-virtual/ar-meme-generator.tsx' },
    { type: 'route', path: '/en/collage-maker', file: '-virtual/en-collage-maker.tsx' },
    { type: 'route', path: '/ar/collage-maker', file: '-virtual/ar-collage-maker.tsx' },
    { type: 'route', path: '/en/image-effects', file: '-virtual/en-image-effects.tsx' },
    { type: 'route', path: '/ar/image-effects', file: '-virtual/ar-image-effects.tsx' },
    { type: 'route', path: '/en/exif-cleaner', file: '-virtual/en-exif-cleaner.tsx' },
    { type: 'route', path: '/ar/exif-cleaner', file: '-virtual/ar-exif-cleaner.tsx' },
    { type: 'route', path: '/en/svg-optimizer', file: '-virtual/en-svg-optimizer.tsx' },
    { type: 'route', path: '/ar/svg-optimizer', file: '-virtual/ar-svg-optimizer.tsx' },
    { type: 'route', path: '/en/mockup-generator', file: '-virtual/en-mockup-generator.tsx' },
    { type: 'route', path: '/ar/mockup-generator', file: '-virtual/ar-mockup-generator.tsx' },
    { type: 'route', path: '/en/image-to-svg', file: '-virtual/en-image-to-svg.tsx' },
    { type: 'route', path: '/ar/image-to-svg', file: '-virtual/ar-image-to-svg.tsx' },
    { type: 'route', path: '/en/seed', file: '-virtual/en-seed.tsx' },
    { type: 'route', path: '/ar/seed', file: '-virtual/ar-seed.tsx' },
    { type: 'route', path: '/en/pix', file: '-virtual/en-pix.tsx' },
    { type: 'route', path: '/ar/pix', file: '-virtual/ar-pix.tsx' },
    { type: 'route', path: '/api/ai/plan', file: '-virtual/api-ai-plan.tsx' },
    { type: 'route', path: '/robots.txt', file: '-virtual/robots.ts' },
    { type: 'route', path: '/sitemap.xml', file: '-virtual/sitemap.ts' },
  ],
};
