import type { SupportedLanguage } from './schema';

export type PixUiText = {
  tune: string; liquify: string; dispersion: string; text: string; historyExport: string;
  openImage: string; formats: string; brightness: string; contrast: string; saturation: string; hue: string; blur: string;
  brushRadius: string; strength: string; particleRadius: string; textPlaceholder: string; addText: string;
  undo: string; redo: string; reset: string; exportPng: string; start: string; localProcessing: string;
};

export const PIX_UI: Record<SupportedLanguage, PixUiText> = {
  en: { tune:'Tune', liquify:'Liquify', dispersion:'Dispersion', text:'Text', historyExport:'History · Export', openImage:'Open image', formats:'JPG, PNG, WebP', brightness:'Brightness', contrast:'Contrast', saturation:'Saturation', hue:'Hue', blur:'Blur', brushRadius:'Brush radius', strength:'Strength', particleRadius:'Particle radius', textPlaceholder:'Enter text here…', addText:'Add text', undo:'Undo', redo:'Redo', reset:'Reset', exportPng:'Export high-resolution PNG', start:'Open an image to start Pix Studio', localProcessing:'Local editing and high-resolution PNG export.' },
  ar: { tune:'الضبط', liquify:'التسييل', dispersion:'التشتت', text:'النص', historyExport:'السجل · التصدير', openImage:'فتح صورة', formats:'JPG وPNG وWebP', brightness:'السطوع', contrast:'التباين', saturation:'التشبع', hue:'درجة اللون', blur:'التمويه', brushRadius:'نصف قطر الفرشاة', strength:'القوة', particleRadius:'نصف قطر الجسيمات', textPlaceholder:'أدخل النص هنا…', addText:'إضافة نص', undo:'تراجع', redo:'إعادة', reset:'إعادة ضبط', exportPng:'تصدير PNG عالي الدقة', start:'افتح صورة للبدء في Pix Studio', localProcessing:'تحرير محلي وتصدير PNG عالي الدقة.' },
  zh: { tune:'调整', liquify:'液化', dispersion:'色散', text:'文字', historyExport:'历史 · 导出', openImage:'打开图片', formats:'JPG、PNG、WebP', brightness:'亮度', contrast:'对比度', saturation:'饱和度', hue:'色相', blur:'模糊', brushRadius:'画笔半径', strength:'强度', particleRadius:'粒子半径', textPlaceholder:'在此输入文字…', addText:'添加文字', undo:'撤销', redo:'重做', reset:'重置', exportPng:'导出高分辨率 PNG', start:'打开图片开始使用 Pix Studio', localProcessing:'本地编辑并导出高分辨率 PNG。' },
  es: { tune:'Ajustes', liquify:'Licuar', dispersion:'Dispersión', text:'Texto', historyExport:'Historial · Exportar', openImage:'Abrir imagen', formats:'JPG, PNG, WebP', brightness:'Brillo', contrast:'Contraste', saturation:'Saturación', hue:'Tono', blur:'Desenfoque', brushRadius:'Radio del pincel', strength:'Intensidad', particleRadius:'Radio de partículas', textPlaceholder:'Escribe el texto aquí…', addText:'Añadir texto', undo:'Deshacer', redo:'Rehacer', reset:'Restablecer', exportPng:'Exportar PNG de alta resolución', start:'Abre una imagen para comenzar con Pix Studio', localProcessing:'Edición local y exportación PNG de alta resolución.' },
  fr: { tune:'Réglages', liquify:'Fluidité', dispersion:'Dispersion', text:'Texte', historyExport:'Historique · Exportation', openImage:'Ouvrir une image', formats:'JPG, PNG, WebP', brightness:'Luminosité', contrast:'Contraste', saturation:'Saturation', hue:'Teinte', blur:'Flou', brushRadius:'Rayon du pinceau', strength:'Intensité', particleRadius:'Rayon des particules', textPlaceholder:'Saisissez le texte ici…', addText:'Ajouter du texte', undo:'Annuler', redo:'Rétablir', reset:'Réinitialiser', exportPng:'Exporter un PNG haute résolution', start:'Ouvrez une image pour commencer avec Pix Studio', localProcessing:'Édition locale et exportation PNG haute résolution.' },
  de: { tune:'Anpassen', liquify:'Verflüssigen', dispersion:'Dispersion', text:'Text', historyExport:'Verlauf · Export', openImage:'Bild öffnen', formats:'JPG, PNG, WebP', brightness:'Helligkeit', contrast:'Kontrast', saturation:'Sättigung', hue:'Farbton', blur:'Unschärfe', brushRadius:'Pinselradius', strength:'Stärke', particleRadius:'Partikelradius', textPlaceholder:'Text hier eingeben…', addText:'Text hinzufügen', undo:'Rückgängig', redo:'Wiederholen', reset:'Zurücksetzen', exportPng:'PNG in hoher Auflösung exportieren', start:'Bild öffnen, um Pix Studio zu starten', localProcessing:'Lokale Bearbeitung und PNG-Export in hoher Auflösung.' },
  pt: { tune:'Ajustes', liquify:'Distorção', dispersion:'Dispersão', text:'Texto', historyExport:'Histórico · Exportação', openImage:'Abrir imagem', formats:'JPG, PNG, WebP', brightness:'Brilho', contrast:'Contraste', saturation:'Saturação', hue:'Matiz', blur:'Desfoque', brushRadius:'Raio do pincel', strength:'Intensidade', particleRadius:'Raio das partículas', textPlaceholder:'Digite o texto aqui…', addText:'Adicionar texto', undo:'Desfazer', redo:'Refazer', reset:'Redefinir', exportPng:'Exportar PNG em alta resolução', start:'Abra uma imagem para começar no Pix Studio', localProcessing:'Edição local e exportação PNG em alta resolução.' },
  ja: { tune:'調整', liquify:'ゆがみ', dispersion:'分散', text:'テキスト', historyExport:'履歴・書き出し', openImage:'画像を開く', formats:'JPG、PNG、WebP', brightness:'明るさ', contrast:'コントラスト', saturation:'彩度', hue:'色相', blur:'ぼかし', brushRadius:'ブラシ半径', strength:'強さ', particleRadius:'粒子半径', textPlaceholder:'ここに文字を入力…', addText:'文字を追加', undo:'元に戻す', redo:'やり直す', reset:'リセット', exportPng:'高解像度 PNG を書き出す', start:'画像を開いて Pix Studio を開始', localProcessing:'ローカル編集と高解像度 PNG の書き出し。' },
  ko: { tune:'조정', liquify:'유동화', dispersion:'분산', text:'텍스트', historyExport:'기록 · 내보내기', openImage:'이미지 열기', formats:'JPG, PNG, WebP', brightness:'밝기', contrast:'대비', saturation:'채도', hue:'색조', blur:'흐림', brushRadius:'브러시 반경', strength:'강도', particleRadius:'입자 반경', textPlaceholder:'여기에 텍스트 입력…', addText:'텍스트 추가', undo:'실행 취소', redo:'다시 실행', reset:'재설정', exportPng:'고해상도 PNG 내보내기', start:'이미지를 열어 Pix Studio 시작', localProcessing:'브라우저에서 로컬 편집 및 고해상도 PNG 내보내기.' },
  ru: { tune:'Настройка', liquify:'Пластика', dispersion:'Дисперсия', text:'Текст', historyExport:'История · Экспорт', openImage:'Открыть изображение', formats:'JPG, PNG, WebP', brightness:'Яркость', contrast:'Контраст', saturation:'Насыщенность', hue:'Оттенок', blur:'Размытие', brushRadius:'Радиус кисти', strength:'Сила', particleRadius:'Радиус частиц', textPlaceholder:'Введите текст здесь…', addText:'Добавить текст', undo:'Отменить', redo:'Повторить', reset:'Сбросить', exportPng:'Экспортировать PNG высокого разрешения', start:'Откройте изображение, чтобы начать работу в Pix Studio', localProcessing:'Локальное редактирование и экспорт PNG высокого разрешения.' },
  it: { tune:'Regolazioni', liquify:'Fluidifica', dispersion:'Dispersione', text:'Testo', historyExport:'Cronologia · Esporta', openImage:'Apri immagine', formats:'JPG, PNG, WebP', brightness:'Luminosità', contrast:'Contrasto', saturation:'Saturazione', hue:'Tonalità', blur:'Sfocatura', brushRadius:'Raggio pennello', strength:'Intensità', particleRadius:'Raggio particelle', textPlaceholder:'Inserisci il testo qui…', addText:'Aggiungi testo', undo:'Annulla', redo:'Ripristina', reset:'Reimposta', exportPng:'Esporta PNG ad alta risoluzione', start:'Apri un’immagine per iniziare con Pix Studio', localProcessing:'Modifica locale ed esportazione PNG ad alta risoluzione.' },
  nl: { tune:'Aanpassen', liquify:'Vervormen', dispersion:'Dispersie', text:'Tekst', historyExport:'Geschiedenis · Export', openImage:'Afbeelding openen', formats:'JPG, PNG, WebP', brightness:'Helderheid', contrast:'Contrast', saturation:'Verzadiging', hue:'Tint', blur:'Vervaging', brushRadius:'Penseelradius', strength:'Sterkte', particleRadius:'Deeltjesradius', textPlaceholder:'Voer hier tekst in…', addText:'Tekst toevoegen', undo:'Ongedaan maken', redo:'Opnieuw', reset:'Resetten', exportPng:'PNG met hoge resolutie exporteren', start:'Open een afbeelding om Pix Studio te starten', localProcessing:'Lokale bewerking en PNG-export met hoge resolutie.' },
  pl: { tune:'Dostosowanie', liquify:'Upłynnianie', dispersion:'Rozpraszanie', text:'Tekst', historyExport:'Historia · Eksport', openImage:'Otwórz obraz', formats:'JPG, PNG, WebP', brightness:'Jasność', contrast:'Kontrast', saturation:'Nasycenie', hue:'Odcień', blur:'Rozmycie', brushRadius:'Promień pędzla', strength:'Siła', particleRadius:'Promień cząstek', textPlaceholder:'Wpisz tekst tutaj…', addText:'Dodaj tekst', undo:'Cofnij', redo:'Ponów', reset:'Resetuj', exportPng:'Eksportuj PNG w wysokiej rozdzielczości', start:'Otwórz obraz, aby rozpocząć w Pix Studio', localProcessing:'Lokalna edycja i eksport PNG w wysokiej rozdzielczości.' },
  tr: { tune:'Ayarla', liquify:'Sıvılaştır', dispersion:'Dağılım', text:'Metin', historyExport:'Geçmiş · Dışa aktar', openImage:'Görsel aç', formats:'JPG, PNG, WebP', brightness:'Parlaklık', contrast:'Kontrast', saturation:'Doygunluk', hue:'Renk tonu', blur:'Bulanıklık', brushRadius:'Fırça yarıçapı', strength:'Güç', particleRadius:'Parçacık yarıçapı', textPlaceholder:'Metni buraya girin…', addText:'Metin ekle', undo:'Geri al', redo:'Yinele', reset:'Sıfırla', exportPng:'Yüksek çözünürlüklü PNG dışa aktar', start:'Pix Studio ile başlamak için bir görsel açın', localProcessing:'Yerel düzenleme ve yüksek çözünürlüklü PNG dışa aktarma.' },
  sv: { tune:'Justering', liquify:'Likvidera', dispersion:'Dispersion', text:'Text', historyExport:'Historik · Export', openImage:'Öppna bild', formats:'JPG, PNG, WebP', brightness:'Ljusstyrka', contrast:'Kontrast', saturation:'Mättnad', hue:'Nyans', blur:'Oskärpa', brushRadius:'Penselradie', strength:'Styrka', particleRadius:'Partikelradie', textPlaceholder:'Ange text här…', addText:'Lägg till text', undo:'Ångra', redo:'Gör om', reset:'Återställ', exportPng:'Exportera PNG i hög upplösning', start:'Öppna en bild för att starta Pix Studio', localProcessing:'Lokal redigering och PNG-export i hög upplösning.' },
  id: { tune:'Penyesuaian', liquify:'Cairkan', dispersion:'Dispersi', text:'Teks', historyExport:'Riwayat · Ekspor', openImage:'Buka gambar', formats:'JPG, PNG, WebP', brightness:'Kecerahan', contrast:'Kontras', saturation:'Saturasi', hue:'Rona', blur:'Buram', brushRadius:'Radius kuas', strength:'Kekuatan', particleRadius:'Radius partikel', textPlaceholder:'Masukkan teks di sini…', addText:'Tambah teks', undo:'Urungkan', redo:'Ulangi', reset:'Atur ulang', exportPng:'Ekspor PNG resolusi tinggi', start:'Buka gambar untuk memulai Pix Studio', localProcessing:'Pengeditan lokal dan ekspor PNG resolusi tinggi.' },
  hi: { tune:'समायोजन', liquify:'लिक्विफाई', dispersion:'विक्षेपण', text:'पाठ', historyExport:'इतिहास · निर्यात', openImage:'चित्र खोलें', formats:'JPG, PNG, WebP', brightness:'चमक', contrast:'कंट्रास्ट', saturation:'संतृप्ति', hue:'रंगछटा', blur:'धुंधलापन', brushRadius:'ब्रश त्रिज्या', strength:'तीव्रता', particleRadius:'कण त्रिज्या', textPlaceholder:'यहाँ पाठ लिखें…', addText:'पाठ जोड़ें', undo:'पूर्ववत', redo:'फिर से करें', reset:'रीसेट', exportPng:'उच्च-रिज़ॉल्यूशन PNG निर्यात करें', start:'Pix Studio शुरू करने के लिए चित्र खोलें', localProcessing:'स्थानीय संपादन और उच्च-रिज़ॉल्यूशन PNG निर्यात।' },
  ur: { tune:'ایڈجسٹ', liquify:'لیکویفائی', dispersion:'ڈسپریشن', text:'متن', historyExport:'ہسٹری · ایکسپورٹ', openImage:'تصویر کھولیں', formats:'JPG، PNG، WebP', brightness:'چمک', contrast:'تضاد', saturation:'سیچوریشن', hue:'ہیو', blur:'بلر', brushRadius:'برش ریڈیئس', strength:'طاقت', particleRadius:'پارٹیکل ریڈیئس', textPlaceholder:'یہاں متن درج کریں…', addText:'متن شامل کریں', undo:'واپس کریں', redo:'دوبارہ کریں', reset:'ری سیٹ', exportPng:'اعلیٰ ریزولوشن PNG برآمد کریں', start:'Pix Studio شروع کرنے کے لیے تصویر کھولیں', localProcessing:'مقامی ترمیم اور اعلیٰ ریزولوشن PNG برآمد۔' },
  vi: { tune:'Điều chỉnh', liquify:'Biến dạng', dispersion:'Phân tán', text:'Văn bản', historyExport:'Lịch sử · Xuất', openImage:'Mở ảnh', formats:'JPG, PNG, WebP', brightness:'Độ sáng', contrast:'Độ tương phản', saturation:'Độ bão hòa', hue:'Sắc độ', blur:'Làm mờ', brushRadius:'Bán kính cọ', strength:'Cường độ', particleRadius:'Bán kính hạt', textPlaceholder:'Nhập văn bản tại đây…', addText:'Thêm văn bản', undo:'Hoàn tác', redo:'Làm lại', reset:'Đặt lại', exportPng:'Xuất PNG độ phân giải cao', start:'Mở ảnh để bắt đầu với Pix Studio', localProcessing:'Chỉnh sửa cục bộ và xuất PNG độ phân giải cao.' },
  th: { tune:'ปรับแต่ง', liquify:'บิดรูป', dispersion:'การกระจาย', text:'ข้อความ', historyExport:'ประวัติ · ส่งออก', openImage:'เปิดภาพ', formats:'JPG, PNG, WebP', brightness:'ความสว่าง', contrast:'คอนทราสต์', saturation:'ความอิ่มสี', hue:'เฉดสี', blur:'เบลอ', brushRadius:'รัศมีแปรง', strength:'ความแรง', particleRadius:'รัศมีอนุภาค', textPlaceholder:'ป้อนข้อความที่นี่…', addText:'เพิ่มข้อความ', undo:'เลิกทำ', redo:'ทำซ้ำ', reset:'รีเซ็ต', exportPng:'ส่งออก PNG ความละเอียดสูง', start:'เปิดภาพเพื่อเริ่มใช้ Pix Studio', localProcessing:'แก้ไขในเครื่องและส่งออก PNG ความละเอียดสูง' },
};
