import type { TranslationSchema, SupportedLanguage } from './schema';

export type ToolUiText = TranslationSchema['commonToolUi'];

const en: ToolUiText = {
  prompt: 'Prompt', promptPlaceholder: 'Describe the image you want to generate…', chooseImage: 'Choose an image', imageInput: 'Image input', outputFormat: 'Output format', scale: 'Scale', backgroundTolerance: 'Background tolerance', svgColumns: 'SVG columns', x: 'X', y: 'Y', width: 'Width', height: 'Height', outputWidth: 'Output width', outputHeight: 'Output height', runTool: 'Run tool', generateImage: 'Generate image', downloadNow: 'Download now', noResult: 'No result yet.', outputDetails: 'Output details', ocrPrivacy: 'OCR runs locally in your browser after loading the engine on demand.', generatorPrivacy: 'This tool requires a configured FLIXO image-generation endpoint.'
};

export const TOOL_UI: Record<SupportedLanguage, ToolUiText> = {
  en,
  ar: { prompt: 'الوصف', promptPlaceholder: 'صف الصورة التي تريد إنشاءها…', chooseImage: 'اختر صورة', imageInput: 'إدخال الصورة', outputFormat: 'صيغة الإخراج', scale: 'المقياس', backgroundTolerance: 'سماحية الخلفية', svgColumns: 'أعمدة SVG', x: 'س', y: 'ص', width: 'العرض', height: 'الارتفاع', outputWidth: 'عرض الإخراج', outputHeight: 'ارتفاع الإخراج', runTool: 'تشغيل الأداة', generateImage: 'إنشاء الصورة', downloadNow: 'تنزيل الآن', noResult: 'لا توجد نتيجة بعد.', outputDetails: 'تفاصيل الإخراج', ocrPrivacy: 'تعمل تقنية OCR محليًا داخل المتصفح بعد تحميل المحرك عند الحاجة.', generatorPrivacy: 'تحتاج هذه الأداة إلى نقطة نهاية مهيأة لتوليد الصور في FLIXO.' },
  zh: { prompt: '提示词', promptPlaceholder: '描述你想生成的图像…', chooseImage: '选择图片', imageInput: '图片输入', outputFormat: '输出格式', scale: '缩放比例', backgroundTolerance: '背景容差', svgColumns: 'SVG 列数', x: 'X', y: 'Y', width: '宽度', height: '高度', outputWidth: '输出宽度', outputHeight: '输出高度', runTool: '运行工具', generateImage: '生成图像', downloadNow: '立即下载', noResult: '暂无结果。', outputDetails: '输出详情', ocrPrivacy: 'OCR 在按需加载引擎后于浏览器本地运行。', generatorPrivacy: '此工具需要配置 FLIXO 图像生成接口。' },
  es: { prompt: 'Indicaciones', promptPlaceholder: 'Describe la imagen que quieres generar…', chooseImage: 'Elegir imagen', imageInput: 'Entrada de imagen', outputFormat: 'Formato de salida', scale: 'Escala', backgroundTolerance: 'Tolerancia del fondo', svgColumns: 'Columnas SVG', x: 'X', y: 'Y', width: 'Ancho', height: 'Alto', outputWidth: 'Ancho de salida', outputHeight: 'Alto de salida', runTool: 'Ejecutar herramienta', generateImage: 'Generar imagen', downloadNow: 'Descargar ahora', noResult: 'Aún no hay resultados.', outputDetails: 'Detalles de salida', ocrPrivacy: 'OCR se ejecuta localmente en el navegador al cargar el motor bajo demanda.', generatorPrivacy: 'Esta herramienta requiere un endpoint de generación de imágenes de FLIXO configurado.' },
  fr: { prompt: 'Invite', promptPlaceholder: 'Décrivez l’image que vous souhaitez générer…', chooseImage: 'Choisir une image', imageInput: 'Entrée image', outputFormat: 'Format de sortie', scale: 'Échelle', backgroundTolerance: 'Tolérance du fond', svgColumns: 'Colonnes SVG', x: 'X', y: 'Y', width: 'Largeur', height: 'Hauteur', outputWidth: 'Largeur de sortie', outputHeight: 'Hauteur de sortie', runTool: 'Exécuter l’outil', generateImage: 'Générer l’image', downloadNow: 'Télécharger maintenant', noResult: 'Aucun résultat pour le moment.', outputDetails: 'Détails de sortie', ocrPrivacy: 'L’OCR s’exécute localement dans le navigateur après le chargement à la demande du moteur.', generatorPrivacy: 'Cet outil nécessite un endpoint FLIXO de génération d’images configuré.' },
  de: { prompt: 'Prompt', promptPlaceholder: 'Beschreiben Sie das gewünschte Bild…', chooseImage: 'Bild auswählen', imageInput: 'Bildeingabe', outputFormat: 'Ausgabeformat', scale: 'Skalierung', backgroundTolerance: 'Hintergrundtoleranz', svgColumns: 'SVG-Spalten', x: 'X', y: 'Y', width: 'Breite', height: 'Höhe', outputWidth: 'Ausgabebreite', outputHeight: 'Ausgabehöhe', runTool: 'Werkzeug ausführen', generateImage: 'Bild erstellen', downloadNow: 'Jetzt herunterladen', noResult: 'Noch kein Ergebnis.', outputDetails: 'Ausgabedetails', ocrPrivacy: 'OCR läuft lokal im Browser, nachdem die Engine bei Bedarf geladen wurde.', generatorPrivacy: 'Dieses Werkzeug benötigt einen konfigurierten FLIXO-Endpunkt zur Bildgenerierung.' },
  pt: { prompt: 'Prompt', promptPlaceholder: 'Descreva a imagem que deseja gerar…', chooseImage: 'Escolher imagem', imageInput: 'Entrada de imagem', outputFormat: 'Formato de saída', scale: 'Escala', backgroundTolerance: 'Tolerância do fundo', svgColumns: 'Colunas SVG', x: 'X', y: 'Y', width: 'Largura', height: 'Altura', outputWidth: 'Largura de saída', outputHeight: 'Altura de saída', runTool: 'Executar ferramenta', generateImage: 'Gerar imagem', downloadNow: 'Baixar agora', noResult: 'Ainda não há resultado.', outputDetails: 'Detalhes da saída', ocrPrivacy: 'O OCR é executado localmente no navegador após o carregamento sob demanda do mecanismo.', generatorPrivacy: 'Esta ferramenta requer um endpoint FLIXO de geração de imagens configurado.' },
  ja: { prompt: 'プロンプト', promptPlaceholder: '生成したい画像を説明してください…', chooseImage: '画像を選択', imageInput: '画像入力', outputFormat: '出力形式', scale: '倍率', backgroundTolerance: '背景許容値', svgColumns: 'SVG 列数', x: 'X', y: 'Y', width: '幅', height: '高さ', outputWidth: '出力幅', outputHeight: '出力高さ', runTool: 'ツールを実行', generateImage: '画像を生成', downloadNow: '今すぐダウンロード', noResult: 'まだ結果はありません。', outputDetails: '出力の詳細', ocrPrivacy: 'OCR はエンジンを必要に応じて読み込み、ブラウザ内でローカル実行します。', generatorPrivacy: 'このツールには FLIXO の画像生成エンドポイントの設定が必要です。' },
  ko: { prompt: '프롬프트', promptPlaceholder: '생성하려는 이미지를 설명하세요…', chooseImage: '이미지 선택', imageInput: '이미지 입력', outputFormat: '출력 형식', scale: '배율', backgroundTolerance: '배경 허용 오차', svgColumns: 'SVG 열 수', x: 'X', y: 'Y', width: '너비', height: '높이', outputWidth: '출력 너비', outputHeight: '출력 높이', runTool: '도구 실행', generateImage: '이미지 생성', downloadNow: '지금 다운로드', noResult: '아직 결과가 없습니다.', outputDetails: '출력 세부 정보', ocrPrivacy: 'OCR은 엔진을 필요할 때 로드한 후 브라우저에서 로컬로 실행됩니다.', generatorPrivacy: '이 도구는 구성된 FLIXO 이미지 생성 엔드포인트가 필요합니다.' },
  ru: { prompt: 'Запрос', promptPlaceholder: 'Опишите изображение, которое хотите создать…', chooseImage: 'Выбрать изображение', imageInput: 'Входное изображение', outputFormat: 'Формат вывода', scale: 'Масштаб', backgroundTolerance: 'Допуск фона', svgColumns: 'Столбцы SVG', x: 'X', y: 'Y', width: 'Ширина', height: 'Высота', outputWidth: 'Ширина результата', outputHeight: 'Высота результата', runTool: 'Запустить инструмент', generateImage: 'Создать изображение', downloadNow: 'Скачать сейчас', noResult: 'Результата пока нет.', outputDetails: 'Сведения о результате', ocrPrivacy: 'OCR выполняется локально в браузере после загрузки движка по запросу.', generatorPrivacy: 'Для этого инструмента требуется настроенная конечная точка генерации изображений FLIXO.' },
  it: { prompt: 'Prompt', promptPlaceholder: 'Descrivi l’immagine che vuoi generare…', chooseImage: 'Scegli immagine', imageInput: 'Input immagine', outputFormat: 'Formato di output', scale: 'Scala', backgroundTolerance: 'Tolleranza sfondo', svgColumns: 'Colonne SVG', x: 'X', y: 'Y', width: 'Larghezza', height: 'Altezza', outputWidth: 'Larghezza output', outputHeight: 'Altezza output', runTool: 'Esegui strumento', generateImage: 'Genera immagine', downloadNow: 'Scarica ora', noResult: 'Nessun risultato ancora.', outputDetails: 'Dettagli output', ocrPrivacy: 'L’OCR viene eseguito localmente nel browser dopo il caricamento su richiesta del motore.', generatorPrivacy: 'Questo strumento richiede un endpoint FLIXO per la generazione di immagini configurato.' },
  nl: { prompt: 'Prompt', promptPlaceholder: 'Beschrijf de afbeelding die je wilt genereren…', chooseImage: 'Afbeelding kiezen', imageInput: 'Afbeeldingsinvoer', outputFormat: 'Uitvoerformaat', scale: 'Schaal', backgroundTolerance: 'Achtergrondtolerantie', svgColumns: 'SVG-kolommen', x: 'X', y: 'Y', width: 'Breedte', height: 'Hoogte', outputWidth: 'Uitvoerbreedte', outputHeight: 'Uitvoerhoogte', runTool: 'Tool uitvoeren', generateImage: 'Afbeelding genereren', downloadNow: 'Nu downloaden', noResult: 'Nog geen resultaat.', outputDetails: 'Uitvoerdetails', ocrPrivacy: 'OCR wordt lokaal in de browser uitgevoerd nadat de engine op verzoek is geladen.', generatorPrivacy: 'Deze tool vereist een geconfigureerd FLIXO-eindpunt voor beeldgeneratie.' },
  pl: { prompt: 'Polecenie', promptPlaceholder: 'Opisz obraz, który chcesz wygenerować…', chooseImage: 'Wybierz obraz', imageInput: 'Wejście obrazu', outputFormat: 'Format wyjściowy', scale: 'Skala', backgroundTolerance: 'Tolerancja tła', svgColumns: 'Kolumny SVG', x: 'X', y: 'Y', width: 'Szerokość', height: 'Wysokość', outputWidth: 'Szerokość wyniku', outputHeight: 'Wysokość wyniku', runTool: 'Uruchom narzędzie', generateImage: 'Wygeneruj obraz', downloadNow: 'Pobierz teraz', noResult: 'Brak wyniku.', outputDetails: 'Szczegóły wyniku', ocrPrivacy: 'OCR działa lokalnie w przeglądarce po wczytaniu silnika na żądanie.', generatorPrivacy: 'To narzędzie wymaga skonfigurowanego endpointu FLIXO do generowania obrazów.' },
  tr: { prompt: 'İstem', promptPlaceholder: 'Oluşturmak istediğiniz görseli açıklayın…', chooseImage: 'Görsel seç', imageInput: 'Görsel girişi', outputFormat: 'Çıktı biçimi', scale: 'Ölçek', backgroundTolerance: 'Arka plan toleransı', svgColumns: 'SVG sütunları', x: 'X', y: 'Y', width: 'Genişlik', height: 'Yükseklik', outputWidth: 'Çıktı genişliği', outputHeight: 'Çıktı yüksekliği', runTool: 'Aracı çalıştır', generateImage: 'Görsel oluştur', downloadNow: 'Şimdi indir', noResult: 'Henüz sonuç yok.', outputDetails: 'Çıktı ayrıntıları', ocrPrivacy: 'OCR motoru gerektiğinde yüklendikten sonra tarayıcıda yerel olarak çalışır.', generatorPrivacy: 'Bu araç yapılandırılmış bir FLIXO görsel oluşturma uç noktası gerektirir.' },
  sv: { prompt: 'Prompt', promptPlaceholder: 'Beskriv bilden du vill skapa…', chooseImage: 'Välj bild', imageInput: 'Bildindata', outputFormat: 'Utdataformat', scale: 'Skala', backgroundTolerance: 'Bakgrundstolerans', svgColumns: 'SVG-kolumner', x: 'X', y: 'Y', width: 'Bredd', height: 'Höjd', outputWidth: 'Utdata­bredd', outputHeight: 'Utdata­höjd', runTool: 'Kör verktyg', generateImage: 'Skapa bild', downloadNow: 'Ladda ner nu', noResult: 'Inget resultat ännu.', outputDetails: 'Utdatadetaljer', ocrPrivacy: 'OCR körs lokalt i webbläsaren efter att motorn laddats vid behov.', generatorPrivacy: 'Det här verktyget kräver en konfigurerad FLIXO-endpoint för bildgenerering.' },
  id: { prompt: 'Prompt', promptPlaceholder: 'Jelaskan gambar yang ingin Anda buat…', chooseImage: 'Pilih gambar', imageInput: 'Input gambar', outputFormat: 'Format keluaran', scale: 'Skala', backgroundTolerance: 'Toleransi latar', svgColumns: 'Kolom SVG', x: 'X', y: 'Y', width: 'Lebar', height: 'Tinggi', outputWidth: 'Lebar keluaran', outputHeight: 'Tinggi keluaran', runTool: 'Jalankan alat', generateImage: 'Buat gambar', downloadNow: 'Unduh sekarang', noResult: 'Belum ada hasil.', outputDetails: 'Detail keluaran', ocrPrivacy: 'OCR berjalan secara lokal di browser setelah mesin dimuat sesuai kebutuhan.', generatorPrivacy: 'Alat ini memerlukan endpoint pembuatan gambar FLIXO yang dikonfigurasi.' },
  hi: { prompt: 'प्रॉम्प्ट', promptPlaceholder: 'वह चित्र बताएं जिसे आप बनाना चाहते हैं…', chooseImage: 'चित्र चुनें', imageInput: 'चित्र इनपुट', outputFormat: 'आउटपुट प्रारूप', scale: 'स्केल', backgroundTolerance: 'पृष्ठभूमि सहनशीलता', svgColumns: 'SVG कॉलम', x: 'X', y: 'Y', width: 'चौड़ाई', height: 'ऊंचाई', outputWidth: 'आउटपुट चौड़ाई', outputHeight: 'आउटपुट ऊंचाई', runTool: 'टूल चलाएँ', generateImage: 'चित्र बनाएं', downloadNow: 'अभी डाउनलोड करें', noResult: 'अभी कोई परिणाम नहीं है।', outputDetails: 'आउटपुट विवरण', ocrPrivacy: 'OCR इंजन को आवश्यकता पर लोड करने के बाद ब्राउज़र में स्थानीय रूप से चलता है।', generatorPrivacy: 'इस टूल के लिए कॉन्फ़िगर किया गया FLIXO इमेज जनरेशन एंडपॉइंट आवश्यक है।' },
  ur: { prompt: 'ہدایات', promptPlaceholder: 'جس تصویر کو بنانا چاہتے ہیں اس کی وضاحت کریں…', chooseImage: 'تصویر منتخب کریں', imageInput: 'تصویر کا ان پٹ', outputFormat: 'آؤٹ پٹ فارمیٹ', scale: 'اسکیل', backgroundTolerance: 'پس منظر کی برداشت', svgColumns: 'SVG کالمز', x: 'X', y: 'Y', width: 'چوڑائی', height: 'اونچائی', outputWidth: 'آؤٹ پٹ چوڑائی', outputHeight: 'آؤٹ پٹ اونچائی', runTool: 'ٹول چلائیں', generateImage: 'تصویر بنائیں', downloadNow: 'ابھی ڈاؤن لوڈ کریں', noResult: 'ابھی کوئی نتیجہ نہیں۔', outputDetails: 'آؤٹ پٹ کی تفصیل', ocrPrivacy: 'OCR انجن کو ضرورت کے وقت لوڈ کرنے کے بعد براؤزر میں مقامی طور پر چلتا ہے۔', generatorPrivacy: 'اس ٹول کے لیے FLIXO کا ترتیب دیا ہوا امیج جنریشن اینڈ پوائنٹ درکار ہے۔' },
  vi: { prompt: 'Mô tả', promptPlaceholder: 'Mô tả hình ảnh bạn muốn tạo…', chooseImage: 'Chọn hình ảnh', imageInput: 'Ảnh đầu vào', outputFormat: 'Định dạng đầu ra', scale: 'Tỷ lệ', backgroundTolerance: 'Dung sai nền', svgColumns: 'Cột SVG', x: 'X', y: 'Y', width: 'Chiều rộng', height: 'Chiều cao', outputWidth: 'Chiều rộng đầu ra', outputHeight: 'Chiều cao đầu ra', runTool: 'Chạy công cụ', generateImage: 'Tạo hình ảnh', downloadNow: 'Tải xuống ngay', noResult: 'Chưa có kết quả.', outputDetails: 'Chi tiết đầu ra', ocrPrivacy: 'OCR chạy cục bộ trong trình duyệt sau khi tải engine theo nhu cầu.', generatorPrivacy: 'Công cụ này yêu cầu endpoint tạo hình ảnh FLIXO được cấu hình.' },
  th: { prompt: 'คำสั่ง', promptPlaceholder: 'อธิบายภาพที่ต้องการสร้าง…', chooseImage: 'เลือกภาพ', imageInput: 'อินพุตภาพ', outputFormat: 'รูปแบบเอาต์พุต', scale: 'มาตราส่วน', backgroundTolerance: 'ค่าความคลาดเคลื่อนของพื้นหลัง', svgColumns: 'คอลัมน์ SVG', x: 'X', y: 'Y', width: 'ความกว้าง', height: 'ความสูง', outputWidth: 'ความกว้างเอาต์พุต', outputHeight: 'ความสูงเอาต์พุต', runTool: 'เรียกใช้เครื่องมือ', generateImage: 'สร้างภาพ', downloadNow: 'ดาวน์โหลดตอนนี้', noResult: 'ยังไม่มีผลลัพธ์', outputDetails: 'รายละเอียดเอาต์พุต', ocrPrivacy: 'OCR ทำงานภายในเบราว์เซอร์หลังโหลดเอนจินเมื่อจำเป็น', generatorPrivacy: 'เครื่องมือนี้ต้องการ endpoint สร้างภาพ FLIXO ที่กำหนดค่าไว้' },
};

export default TOOL_UI;
