import fs from "node:fs";
import path from "node:path";
import { logErrorToSink } from "../error-sink.mjs";
const ROOT = process.cwd();
const RULES_FILE = path.join(ROOT, "REGRESSION_RULES.json");
const SHA_REGEX = /^[a-f0-9]{40}$/i;
const MAX_RULES = 200;
const MAX_PATTERN_LENGTH = 240;
function safeTarget(p) { return typeof p === "string" && p.length > 0 && p.length <= 260 && !path.isAbsolute(p) && !p.includes("\\") && path.posix.normalize(p) === p && !p.startsWith("../") && !p.includes("/../"); }
function unsafePattern(p) { if (typeof p !== "string" || p.length < 3 || p.length > MAX_PATTERN_LENGTH) return true; if (/^(?:\.\*|\.\+|\(\?:?\.\*\)|\(\?:?\.\+\))$/.test(p)) return true; if (/\(\?[:=!<]/.test(p)) return true; if (/\((?:[^()\\]|\\.)*[*+](?:[^()\\]|\\.)*\)[*+]/.test(p)) return true; let c = 0; for (const t of p) { if (t === "|") c += 2; if (t === "*") c += 2; if (t === "+") c += 2; if (t === "?") c += 1; if (t === "(") c += 1; } return c > 18; }
export function validateRule(r) { if (!r || typeof r !== "object") return { valid:false, reason:"Rule must be an object" }; if (!r.id || !r.targetFile || !r.bannedPattern || !r.fixSha) return {valid:false, reason:"Missing mandatory fields"}; if (typeof r.id !== "string" || r.id.length > 160) return {valid:false, reason:"Invalid rule id"}; if (!SHA_REGEX.test(r.fixSha)) return {valid:false, reason:"fixSha must be 40 hexadecimal chars"}; if (!safeTarget(r.targetFile)) return {valid:false, reason:"Unsafe repository-relative targetFile"}; if (unsafePattern(r.bannedPattern)) return {valid:false, reason:"Unsafe or overly broad regex"}; try { new RegExp(r.bannedPattern); } catch (e) { return {valid:false, reason:`Invalid regex: ${e.message}`}; } if (!["blocking","advisory"].includes(r.guardMode)) return {valid:false, reason:"guardMode must be blocking or advisory"}; return {valid:true}; }
export function runRegressionGuard() { if (!fs.existsSync(RULES_FILE)) return 0; let parsed; try { parsed = JSON.parse(fs.readFileSync(RULES_FILE,"utf8")); } catch (e) { logErrorToSink({toolName:"regression-guard",severity:"CRITICAL",signature:"REGRESSION_RULES_INVALID",rootCause:"REGRESSION_RULES.json is not valid JSON",details:e.stack||String(e)}); return 1; } const rules = Array.isArray(parsed) ? parsed : parsed?.rules; if (!Array.isArray(rules)) { logErrorToSink({toolName:"regression-guard",severity:"CRITICAL",signature:"REGRESSION_RULES_INVALID",rootCause:"REGRESSION_RULES.json must contain a rule array",details:"Invalid schema"}); return 1; } let exitCode=0; for (const rule of rules.slice(0,MAX_RULES)) { const v=validateRule(rule); if (!v.valid) { logErrorToSink({toolName:"regression-guard",severity:"CRITICAL",signature:"REGRESSION_RULE_INVALID",rootCause:v.reason,details:JSON.stringify(rule)}); exitCode=1; continue; } const target=path.resolve(ROOT,rule.targetFile); if (!target.startsWith(ROOT+path.sep)) { logErrorToSink({toolName:"regression-guard",severity:"CRITICAL",signature:"REGRESSION_TARGET_ESCAPE",rootCause:"Rule resolves outside repository root",details:rule.targetFile}); exitCode=1; continue; } if (!fs.existsSync(target)) continue; const match=new RegExp(rule.bannedPattern).test(fs.readFileSync(target,"utf8")); if (!match) continue; const blocking=rule.guardMode === "blocking"; logErrorToSink({toolName:"regression-guard",severity:blocking?"CRITICAL":"WARNING",signature:`${blocking?"REGRESSION_CONFIRMED":"POSSIBLE_REGRESSION"}:${rule.id}`,rootCause:`Previously fixed pattern matched in ${rule.targetFile}`,details:`Fixed in SHA ${rule.fixSha}. Required pattern: ${rule.requiredPattern||"not specified"}`}); if (blocking) exitCode=1; } return exitCode; }
if (import.meta.url === `file://${process.argv[1]}`) process.exitCode = runRegressionGuard();
